plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/gabrielpaiva/Movies/Operation_Hotmart_Mastery/arsenal-sovereign-stack"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]